[package]
name = "sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true } 
serde_json = { workspace = true }
